<template>
  <div>
    <detail v-bind="detailData"/>
    <el-button @click="setValue">给第二层数据赋值</el-button>
    <buttons-operator type="bottom"
                      :buttons="[{label:'提交',type:'primary',click:sumbit},{label:'返回',type:'info',click:back}]"/>
  </div>
</template>
<script>
  import detail from '@/components/Detail.vue'
  import buttonsOperator from '@/components/ButtonsOperator.vue'

  export default {
    components:{
      detail,
      buttonsOperator
    },
    data() {
      return {
        data1:{
          prop1:'value1',
          prop2:'value2',
          prop3:'value3',
          prop4:'value4',
          prop5:'value5',
          prop6:'value6',
          prop7:'value7',
          files:[{name:'文件测试',url:'test'}],
        },
        data2:{}
      };
    },
    computed:{
      detailData(){
        return {contents:[
          {
            header:'标题',
            labelWidth:'200px',
            data:this.data1,
            children:[
              {
                type:'label',
                label:'label1',
                prop:'prop1',
              },
              {
                type:'label',
                label:'label2',
                prop:'prop2',
              },
              {
                type:'label',
                label:'label3',
                prop:'prop3',
              },
              {
                type:'file',
                label:'file4',
                prop:'files',
              },
              {
                type:'file',
                label:'file5',
                prop:'files',
              },
              {
                type:'file',
                label:'file6',
                prop:'files',
              },
              {
                type:'file',
                label:'file7',
                prop:'files',
              }
            ]
          },
          {
            header:'标题2',
            data:this.data2,
            labelWidth:'200px',
            children:[
              {
                type:'label',
                label:'label1',
                prop:'prop1',
              },
              {
                type:'label',
                label:'label2',
                prop:'prop2',
              },
              {
                type:'label',
                label:'label3',
                prop:'prop3',
              },
              {
                type:'file',
                label:'file4',
                prop:'files',
              },
              {
                type:'file',
                label:'file5',
                prop:'files',
              },
              {
                type:'file',
                label:'file6',
                prop:'files',
              },
              {
                type:'file',
                label:'file7',
                prop:'files',
              }
            ]
          }
        ]}
      }
    },
    methods:{
      setValue(){
        this.data2=this.data1
        this.detailData.contents[1].data=this.data1;
      },
      sumbit(){
        console.log('sumbit')
      },
      back(){
        console.log('back')
      }
    },
    created(){
      console.log(this.$route.params.id)
    }
  }
</script>
