<template>
  <detail v-bind="detailData"></detail>
</template>
<script>
  import detail from '@/components/Detail.vue'

  export default {
    components:{
      detail
    },
    data() {
      return {
        detailData:{
          contents:[
            {
              header:'标题',
              children:[
                {
                  type:'label',
                  label:'label1',
                  value:'value',
                },
                {
                  type:'label',
                  label:'label2',
                  value:'value',
                },
                {
                  type:'label',
                  label:'label3',
                  value:'value',
                },
                {
                  type:'file',
                  label:'file4',
                  value:'fileName',
                  url:'fileUrl',
                },
                {
                  type:'file',
                  label:'file5',
                  value:'fileName',
                  url:'fileUrl',
                },
                {
                  type:'file',
                  label:'file6',
                  value:'fileName',
                  url:'fileUrl',
                },
                {
                  type:'file',
                  label:'file7',
                  value:'fileName',
                  url:'fileUrl',
                }
              ]
            },
            {
              header:'标题2',
              children:[
                {
                  type:'label',
                  label:'label1',
                  value:'value',
                },
                {
                  type:'label',
                  label:'label2',
                  value:'value',
                },
                {
                  type:'label',
                  label:'label3',
                  value:'value',
                },
                {
                  type:'file',
                  label:'file4',
                  value:'fileName',
                  url:'fileUrl',
                },
                {
                  type:'file',
                  label:'file5',
                  value:'fileName',
                  url:'fileUrl',
                },
                {
                  type:'file',
                  label:'file6',
                  value:'fileName',
                  url:'fileUrl',
                },
                {
                  type:'file',
                  label:'file7',
                  value:'fileName',
                  url:'fileUrl',
                }
              ]
            }
          ]
        }
      };
    }
  }
</script>
