<template>
  <div>
    <detail v-bind="detailData"></detail>
    <el-button @click="setValue">给第二层数据赋值</el-button>
  </div>


</template>
<script>
  import detail from '@/components/Detail.vue'

  export default {
    components:{
      detail
    },
    data() {
      return {
        data1:{
          prop1:'value1',
          prop2:'value2',
          prop3:'value3',
          prop4:'value4',
          prop5:'value5',
          prop6:'value6',
          prop7:'value7',
          fileUrl4:'fileUrl4',
          fileUrl5:'fileUrl5',
          fileUrl6:'fileUrl6',
          fileUrl7:'fileUrl7',
        },
        data2:{}
      };
    },
    computed:{
      detailData(){
        return {contents:[
          {
            header:'标题',
            data:this.data1,
            children:[
              {
                type:'label',
                label:'label1',
                prop:'prop1',
              },
              {
                type:'label',
                label:'label2',
                prop:'prop2',
              },
              {
                type:'label',
                label:'label3',
                prop:'prop3',
              },
              {
                type:'file',
                label:'file4',
                prop:'prop4',
                prop_url:'fileUrl4',
              },
              {
                type:'file',
                label:'file5',
                prop:'prop5',
                prop_url:'fileUrl5',
              },
              {
                type:'file',
                label:'file6',
                prop:'prop6',
                prop_url:'fileUrl6',
              },
              {
                type:'file',
                label:'file7',
                prop:'prop7',
                prop_url:'fileUrl7',
              }
            ]
          },
          {
            header:'标题2',
            data:this.data2,
            children:[
              {
                type:'label',
                label:'label1',
                prop:'prop1',
              },
              {
                type:'label',
                label:'label2',
                prop:'prop2',
              },
              {
                type:'label',
                label:'label3',
                prop:'prop3',
              },
              {
                type:'file',
                label:'file4',
                prop:'prop4',
                prop_url:'fileUrl4',
              },
              {
                type:'file',
                label:'file5',
                prop:'prop5',
                prop_url:'fileUrl5',
              },
              {
                type:'file',
                label:'file6',
                prop:'prop6',
                prop_url:'fileUrl6',
              },
              {
                type:'file',
                label:'file7',
                prop:'prop7',
                prop_url:'fileUrl7',
              }
            ]
          }
        ]}
      }
    },
    methods:{
      setValue(){
        this.data2=this.data1
        this.detailData.contents[1].data=this.data1;
      }
    }
  }
</script>
